# Global Config
SinatraPort: 9997
X_RESTJmeter_TOKEN: "UkVTVEptZXRlcl9UT0tFTg==" # Header for Auth
DataBase_Connection: "postgres://postgres:root@10.249.73.210:5432/jmeter_auto_results"
User_Defined_Vars_CSV_Dir: "/Users/yanli6/Personal/DevDir/Code/rubymine/jmeter_auto_rest_service/test/csv_data_set_files/"
JMX_File_DIR: "/Users/yanli6/Personal/DevDir/Code/rubymine/jmeter_auto_rest_service/test" # Absolute dir path for jmx files
JMeter_Reside_OS: "OSX"
JMeter_Home: "/Users/yanli6/Personal/DevDir/DevTools/apache-jmeter-2.13"
Aggregate_Results_Dir: "/Users/yanli6/Personal/DevDir/Code/rubymine/jmeter_auto_rest_service/test/aggregate_results"

ThreadGroup_RampUpPeriod_Default: 0

System_Log_File: "/Users/yanli6/Personal/DevDir/Code/rubymine/testproj/xmltest/xmlfile/system_log.log"
System_Log_Level: "DEBUG"

Aggregate_Error_Rate_Threshold: 10
